version: "3.8"
services:
  cat_obtainer:
    init: true
    container_name: cat_obtainer
    image: alpine/curl:8.7.1
    volumes:
      - app-volume:/var/
    command: curl https://streetcat.wiki/images/5/50/Freshlycat.png -o /var/cat.png

  frontend:
    env_file: .env
    container_name: frontend
    build:
      context: ../services/frontend
    networks:
      - app-network
    ports:
      - ${FRONTEND_PORT}:8080
    volumes:
      - app-volume:/usr/share/nginx/html/storage
    depends_on:
      - backend
      - cat_obtainer
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  backend:
    env_file: .env
    depends_on:
      - cat_obtainer
    container_name: backend
    build:
      context: ../services/backend
    networks:
      - app-network
    ports:
      - ${BACKEND_PORT}:3000

networks:
  app-network:
    driver: bridge

volumes:
  app-volume:
