apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: danyakladnitsky/itmo-devops-course.frontend:v1.2
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-volume
              mountPath: /usr/share/nginx/html/storage
      volumes:
        - name: app-volume
          emptyDir: {}
      initContainers:
        - name: init-container
          image: alpine/curl:8.7.1
          command:
            [
              "curl",
              "https://streetcat.wiki/images/5/50/Freshlycat.png",
              "-o",
              "/var/cat.png",
            ]
