FROM node:latest

ADD . .
RUN npm install
RUN npm run build
ADD nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*

COPY /dist /usr/share/nginx/html/frontend-app
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]