FROM node:latest as builder

ADD . .
RUN npm install
RUN npm run build


FROM nginx:latest as production-build
ADD nginx/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /dist /usr/share/nginx/html/frontend-app

CMD ["nginx", "-g", "daemon off;"]